data <-c(10,11,12,13,14,15,16,17,18,14,13,19,13,10,20)
print("dataset")
print(data)
mean<-mean(data)
print(paste("mean =",mean))
median<-median(data)
print(paste("median=",median))
mode<-function(x){
  uniq<-unique(x)
  uniq[which.max(tabulate(match(x,uniq)))]
}
mode_v<-mode(data)
print(paste("mode=",mode_v))
max<-max(data)
print(paste("max->",max))
min<-min(data)
print(paste("min->",min))
variance<-var(data)
print(paste("var=",variance))
sd<-sd(data)
print(paste("std=",sd))
summary(data)
barplot(data)
line(data)
lines(data)
hist(data)
pie(data)
boxplot(data)
scatter.smooth(data)

