use ds;
select * from weatherhistory;
select * from wh;
desc wh;
insert into wh values ('2010-05-18 01:12:23' ,'rain',23.875);
select datediff(sysdate(),summary) from wh;
select date_format("2007-05-15","%y");
select quarter("2006-04-01");
 select adddate("2011-03-23 03:34:12" ,interval 10 DAY) ;
  select adddate("2011-03-23 03:34:12" ,interval 10 year) ;
select date_sub(now(),interval 7 Day);
select dayname("2011-03-23 03:34:12");
select day(now());
select dayname(now());

select *from emp;
select *from emp1;
alter table emp drop column salary;
select *from info;
select* from emp1 where f_name like 'r%' or f_name like 'v%'  ;
select * from emp1 where f_name regexp '^v';
select * from emp1 where f_name regexp '[u-v,x]';
select * from emp1 where f_name regexp '[sv]';
select * from emp1 where f_name regexp '^ven';
select * from emp1 where f_name regexp '[ven-vig,x]';
select f_name from emp1 where salary>(select avg(salary) from emp1);
select max(age) from info where age<(select max(age) from info where age<(select max(age) from info ));
select max(age) from info where age<>(select max(age) from info);
select distinct age from info order by age desc limit 1 offset 2;

create view em as select  *from info where age>30;
create view v1_emp as select *from emp where salary>15000;
create view v2_emp as select *from emp1 where designation ='DS';
select*from v1_emp;
select*from v2_emp;
select*from em;
drop view em1;
create view em as select join1.s_name,join2.t_name from join1 inner join join2 on join1.total =join2.total; 
select * from em;
create view em1 as select e1.l_name,e.emp_name from emp1 e1 join emp e  where e.emp_name=e1.f_name and e1.f_name='venky';
select * from em1;
