use ds;
create table emp ( emp_id int primary key auto_increment,emp_name varchar(20) not null,salary int );
drop table emp;
select *from emp;
desc table emp;
select * from emp order by emp_id asc;
alter table emp modify emp_name varchar(20) unique;
alter table emp add job varchar(20);
alter table emp drop column job;
insert into emp(emp_name,salary) values('venky',30000),('chatan',21100),('shiva',25000);
select count('data_column') from emp;
update  emp set salary=25000 WHERE emp_id=2;
truncate emp;
delete from emp where emp_id=3;
ALTER TABLE emp ADD UNIQUE (emp_name);
select sum(salary) from emp;
select avg(salary) from emp;

desc info;
drop table info;
create table info ( f_name varchar(20),l_name varchar(20) ,id int primary key auto_increment,age int,city varchar(20),state varchar(20)); 
insert into info (f_name,l_name,age,state,city) values("arjun","reddy",29 ,"hyd","ban"),("konda","reddy", 45,"mad","ban"),("ballem","reddy",31 ,"hyd","ban"),("vejay","reddy",21 ,"ves","ban");
alter table info Add unique (info_id);
select* from info;
select f_name,l_name from info where age>25;
select count(*) from info where age>25 and age<45;
select count('data_column') from info;
select * from info where f_name  like 'a%';
select * from info where f_name  like '%a';
select * from info where l_name  like '%dd%';
Alter table info rename column id to info_id;
select count(*) from info where age=25 or age=45;
select * from info where age  in (45,21);

drop table emp1;
create table  emp1 (f_name varchar(20),l_name varchar(20),designation varchar(30),age int ,salary float(4));
insert into emp1 values ('venky','raju','securatry',46,200000.00),('raju','ram','employ',23,11100.00),('rakesh','master','programmer',34,600000.00),('vignash','garu','hacker',26,45000.00),('sai','gara','programer',67,67111.00);
select * from emp1;

set sql_safe_updates=0;
update emp1 set l_name='uhicha' where f_name= 'raju';
update emp1 set designation = 'pro.programmer' where  designation = 'programmer';
update emp1 set salary=+10000 where salary>100000;
update emp1 set salary=+60000 where salary<100000;
update  emp1 set designation = 'data analysis' where age =46; 
update  emp1 set designation = 'data science', age=+1 where f_name ='venky'; 
update emp1 set designation = 'pro.programmer' where  designation = 'programer';
update emp1 set designation = 'pro.programmer1' where  designation = 'pro.programmer2';
delete from emp1 where  designation = 'pro.programmer1';
