# -*- coding: utf-8 -*-
"""py_base2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AyDGryzi4w7nTkBn7ZZCrdnPp1g8MQUO

**function**
"""

def even_odd(num):
  if num %2 ==0:
    print("num even")
  else:
    print("num odd")

even_odd(130257283689136951707)
even_odd(130257283689136951708)

def fact(n):
  f=1
  for i in range(1,n+1):
    f=f*i
  return f

fact(345)

def sum(n):
  num=0
  for i in range(1,n+1):
    num=num+i
  return num

sum(567)

def fun(name,age="null"):
  print("name:",name,"age:",age)

fun("venky",21)

""" **lambda fun**"""

x=lambda a:a+12
print(x(13))

x=lambda a:"even" if a%2==0 else "Odd"
print(x(1234))

x= lambda a,b:a**b
print(x(3003,600))

def check_palindrome(input):
  reverse = input[::-1]
  if input == reverse:
    print("palindrome")
  else:
    print("not palindrome")

check_palindrome("sdds")

"""**MAP REDUSING AND FILTER:**"""

import math
def area(r):
  return math.pi*(r**2)
  radius=[1,2,3,4,5]
  area=[]
  for r in radius:
    area.append(area(r))
  print(area)

area(5)

list(map(area,[1,2,3,4,5]))

temp=[("mumbai",23),("mahestera",33),("talangana",41)]
len(temp)

call=lambda data:(data[0],(9/5)*data[1]+32)
print(call(temp[2]))

list(map(call,temp))

import statistics
data=[1.3,2.7,0.8,4.1,4.3,-0.1]
avg=statistics.mean(data)
print(avg)
filter(lambda x:x>avg,data)

list(filter(lambda x:x>avg,data))

filter(lambda x:x>1.5,data)

num=["a","",0,0.0,"b","c"]

filter(None,num)
list(filter(None,num))

from functools import reduce
data=[1,12,435,1,23]
mul=lambda x,y:x*y

reduce(mul,data)

from functools import reduce
data=[1,12,435,1,23]
Sub=lambda x,y:x-y
reduce(Sub,data)

with open("venky.txt","w") as file:
    file.write("venky\n")
    file.write("hello world\n")
    file.write("hellow world\n")

file =open("venky.txt","r")
print(file.read())

file =  open("sample.txt","w")

with open("venky.txt","a") as file:
  file.write("these is a privat party\n")
  file.write("buncay tensa zanziseu\n")

file =open ("sample.txt","r")

for line in file:
  print(line)

import pandas as pd
df=pd.read_csv('/content/cleaned_global_water_consumption (1).csv')
df.head()

sales=[25000,30000,450000,50000]

cal=lambda cal: int(cal*0.10)+cal

list(map(cal, sales))

marks=[45,67,89,34,78,55,90]
x=lambda mark: (mark>60)
list(filter(x, marks))

sales =[1200,1500,1800,2100]
s= lambda x,y:x+y
reduce(s,sales)

sales =[2,5,8,11,14,15]
a=lambda x: x % 2 == 0
sale= [num**2 for num in sales]
list(filter(a, sale))

from functools import reduce
sales=[25000,40000,55000,30000,70000]
a=lambda x: x >30000
reduce(lambda x,y:x+y,list(filter(a,sales)))

